version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sent-db
    ports:
      - "2345:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sent_network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: ljj27257@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - sent_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  sent_network: