version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "2345:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sent_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  sent_network: