import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="w-3/4 m-auto font-light font-sans invis-par">
      
        <div className="flex items-end gap-10 pb-2 max-md:text-sm max-sm:gap-2 max-md:gap-5">
          <Link href="/">
            <h2 className="pt-5 xl:text-5xl max-xl:text-3xl max-md:text-lg max-sm:w-0 max-sm:invisible">Sentiment.JS</h2>
          </Link>
          <Link href="/examples" className="hover:bg-white hover:text-gray-800 xl:text-xl">Examples</Link>
          <Link href="https://github.com/lukasjanusauskas/sentiment-js" className="hover:bg-white hover:text-gray-800 xl:text-xl max-md:w-0 max-md:invisible">Development</Link>
          <div className="flex-grow"></div>
          <Link href="/signup" className="hover:bg-white hover:text-gray-800 xl:text-xl">Sign up</Link>
          <Link href="/login" className="hover:bg-white hover:text-gray-800 xl:text-xl">Log In</Link>
        </div>
        <hr className="invisible max-md:visible"></hr>


    </div>
        {children}
      </body>
    </html>
  );
}
